<?php
/**
 * MediaApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * MediaApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MediaApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'v1AccountAccountIDMediaMediaIDFileGet' => [
            'application/json',
        ],
        'v1AccountAccountIDMediaMediaIDFilePost' => [
            'multipart/form-data',
        ],
        'v1AccountAccountidMediaGet' => [
            'application/json',
        ],
        'v1AccountAccountidMediaMediaidDelete' => [
            'application/json',
        ],
        'v1AccountAccountidMediaMediaidGet' => [
            'application/json',
        ],
        'v1AccountAccountidMediaPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1AccountAccountIDMediaMediaIDFileGet
     *
     * Get Media File
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $media_id Media ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMediaMediaIDFileGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SplFileObject|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountAccountIDMediaMediaIDFileGet($account_id, $media_id, string $contentType = self::contentTypes['v1AccountAccountIDMediaMediaIDFileGet'][0])
    {
        list($response) = $this->v1AccountAccountIDMediaMediaIDFileGetWithHttpInfo($account_id, $media_id, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountAccountIDMediaMediaIDFileGetWithHttpInfo
     *
     * Get Media File
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $media_id Media ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMediaMediaIDFileGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountAccountIDMediaMediaIDFileGetWithHttpInfo($account_id, $media_id, string $contentType = self::contentTypes['v1AccountAccountIDMediaMediaIDFileGet'][0])
    {
        $request = $this->v1AccountAccountIDMediaMediaIDFileGetRequest($account_id, $media_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\SplFileObject',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\SplFileObject',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SplFileObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountAccountIDMediaMediaIDFileGetAsync
     *
     * Get Media File
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $media_id Media ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMediaMediaIDFileGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMediaMediaIDFileGetAsync($account_id, $media_id, string $contentType = self::contentTypes['v1AccountAccountIDMediaMediaIDFileGet'][0])
    {
        return $this->v1AccountAccountIDMediaMediaIDFileGetAsyncWithHttpInfo($account_id, $media_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountAccountIDMediaMediaIDFileGetAsyncWithHttpInfo
     *
     * Get Media File
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $media_id Media ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMediaMediaIDFileGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMediaMediaIDFileGetAsyncWithHttpInfo($account_id, $media_id, string $contentType = self::contentTypes['v1AccountAccountIDMediaMediaIDFileGet'][0])
    {
        $returnType = '\SplFileObject';
        $request = $this->v1AccountAccountIDMediaMediaIDFileGetRequest($account_id, $media_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountAccountIDMediaMediaIDFileGet'
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $media_id Media ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMediaMediaIDFileGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountAccountIDMediaMediaIDFileGetRequest($account_id, $media_id, string $contentType = self::contentTypes['v1AccountAccountIDMediaMediaIDFileGet'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling v1AccountAccountIDMediaMediaIDFileGet'
            );
        }

        // verify the required parameter 'media_id' is set
        if ($media_id === null || (is_array($media_id) && count($media_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $media_id when calling v1AccountAccountIDMediaMediaIDFileGet'
            );
        }


        $resourcePath = '/v1/account/{accountID}/media/{mediaID}/file';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountID' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($media_id !== null) {
            $resourcePath = str_replace(
                '{' . 'mediaID' . '}',
                ObjectSerializer::toPathValue($media_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'audio/mp3', 'audio/mpeg', 'audio/mpeg3', 'audio/x-wav', 'audio/wav', 'audio/ogg', 'video/x-flv', 'video/h264', 'video/mpeg', 'video/quicktime', 'video/mp4', 'video/webm', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountAccountIDMediaMediaIDFilePost
     *
     * Add Media File
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $media_id Media ID, 32 alpha numeric (required)
     * @param  \SplFileObject $file Media file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMediaMediaIDFilePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ServiceDocsMediaGetSingle|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountAccountIDMediaMediaIDFilePost($account_id, $media_id, $file, string $contentType = self::contentTypes['v1AccountAccountIDMediaMediaIDFilePost'][0])
    {
        list($response) = $this->v1AccountAccountIDMediaMediaIDFilePostWithHttpInfo($account_id, $media_id, $file, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountAccountIDMediaMediaIDFilePostWithHttpInfo
     *
     * Add Media File
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $media_id Media ID, 32 alpha numeric (required)
     * @param  \SplFileObject $file Media file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMediaMediaIDFilePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ServiceDocsMediaGetSingle|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountAccountIDMediaMediaIDFilePostWithHttpInfo($account_id, $media_id, $file, string $contentType = self::contentTypes['v1AccountAccountIDMediaMediaIDFilePost'][0])
    {
        $request = $this->v1AccountAccountIDMediaMediaIDFilePostRequest($account_id, $media_id, $file, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountAccountIDMediaMediaIDFilePostAsync
     *
     * Add Media File
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $media_id Media ID, 32 alpha numeric (required)
     * @param  \SplFileObject $file Media file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMediaMediaIDFilePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMediaMediaIDFilePostAsync($account_id, $media_id, $file, string $contentType = self::contentTypes['v1AccountAccountIDMediaMediaIDFilePost'][0])
    {
        return $this->v1AccountAccountIDMediaMediaIDFilePostAsyncWithHttpInfo($account_id, $media_id, $file, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountAccountIDMediaMediaIDFilePostAsyncWithHttpInfo
     *
     * Add Media File
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $media_id Media ID, 32 alpha numeric (required)
     * @param  \SplFileObject $file Media file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMediaMediaIDFilePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMediaMediaIDFilePostAsyncWithHttpInfo($account_id, $media_id, $file, string $contentType = self::contentTypes['v1AccountAccountIDMediaMediaIDFilePost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle';
        $request = $this->v1AccountAccountIDMediaMediaIDFilePostRequest($account_id, $media_id, $file, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountAccountIDMediaMediaIDFilePost'
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $media_id Media ID, 32 alpha numeric (required)
     * @param  \SplFileObject $file Media file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMediaMediaIDFilePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountAccountIDMediaMediaIDFilePostRequest($account_id, $media_id, $file, string $contentType = self::contentTypes['v1AccountAccountIDMediaMediaIDFilePost'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling v1AccountAccountIDMediaMediaIDFilePost'
            );
        }

        // verify the required parameter 'media_id' is set
        if ($media_id === null || (is_array($media_id) && count($media_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $media_id when calling v1AccountAccountIDMediaMediaIDFilePost'
            );
        }

        // verify the required parameter 'file' is set
        if ($file === null || (is_array($file) && count($file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $file when calling v1AccountAccountIDMediaMediaIDFilePost'
            );
        }


        $resourcePath = '/v1/account/{accountID}/media/{mediaID}/file';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountID' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($media_id !== null) {
            $resourcePath = str_replace(
                '{' . 'mediaID' . '}',
                ObjectSerializer::toPathValue($media_id),
                $resourcePath
            );
        }

        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'file' => $file,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountAccountidMediaGet
     *
     * Get Media List
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key start_key for pagination that was returned as next_start_key from your previous call (optional)
     * @param  int|null $page_size number of records to return, range 1 to 50 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ServiceDocsMediaGetAll|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountAccountidMediaGet($accountid, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountidMediaGet'][0])
    {
        list($response) = $this->v1AccountAccountidMediaGetWithHttpInfo($accountid, $start_key, $page_size, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountAccountidMediaGetWithHttpInfo
     *
     * Get Media List
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key start_key for pagination that was returned as next_start_key from your previous call (optional)
     * @param  int|null $page_size number of records to return, range 1 to 50 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ServiceDocsMediaGetAll|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountAccountidMediaGetWithHttpInfo($accountid, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountidMediaGet'][0])
    {
        $request = $this->v1AccountAccountidMediaGetRequest($accountid, $start_key, $page_size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ServiceDocsMediaGetAll',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ServiceDocsMediaGetAll',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ServiceDocsMediaGetAll',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountAccountidMediaGetAsync
     *
     * Get Media List
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key start_key for pagination that was returned as next_start_key from your previous call (optional)
     * @param  int|null $page_size number of records to return, range 1 to 50 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountidMediaGetAsync($accountid, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountidMediaGet'][0])
    {
        return $this->v1AccountAccountidMediaGetAsyncWithHttpInfo($accountid, $start_key, $page_size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountAccountidMediaGetAsyncWithHttpInfo
     *
     * Get Media List
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key start_key for pagination that was returned as next_start_key from your previous call (optional)
     * @param  int|null $page_size number of records to return, range 1 to 50 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountidMediaGetAsyncWithHttpInfo($accountid, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountidMediaGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ServiceDocsMediaGetAll';
        $request = $this->v1AccountAccountidMediaGetRequest($accountid, $start_key, $page_size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountAccountidMediaGet'
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key start_key for pagination that was returned as next_start_key from your previous call (optional)
     * @param  int|null $page_size number of records to return, range 1 to 50 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountAccountidMediaGetRequest($accountid, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountidMediaGet'][0])
    {

        // verify the required parameter 'accountid' is set
        if ($accountid === null || (is_array($accountid) && count($accountid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accountid when calling v1AccountAccountidMediaGet'
            );
        }




        $resourcePath = '/v1/account/{accountid}/media';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_key,
            'start_key', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'page_size', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($accountid !== null) {
            $resourcePath = str_replace(
                '{' . 'accountid' . '}',
                ObjectSerializer::toPathValue($accountid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountAccountidMediaMediaidDelete
     *
     * Delete Media
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string $mediaid Device ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaMediaidDelete'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ServiceDocsMediaGetSingle|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountAccountidMediaMediaidDelete($accountid, $mediaid, string $contentType = self::contentTypes['v1AccountAccountidMediaMediaidDelete'][0])
    {
        list($response) = $this->v1AccountAccountidMediaMediaidDeleteWithHttpInfo($accountid, $mediaid, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountAccountidMediaMediaidDeleteWithHttpInfo
     *
     * Delete Media
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string $mediaid Device ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaMediaidDelete'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ServiceDocsMediaGetSingle|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountAccountidMediaMediaidDeleteWithHttpInfo($accountid, $mediaid, string $contentType = self::contentTypes['v1AccountAccountidMediaMediaidDelete'][0])
    {
        $request = $this->v1AccountAccountidMediaMediaidDeleteRequest($accountid, $mediaid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountAccountidMediaMediaidDeleteAsync
     *
     * Delete Media
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string $mediaid Device ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaMediaidDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountidMediaMediaidDeleteAsync($accountid, $mediaid, string $contentType = self::contentTypes['v1AccountAccountidMediaMediaidDelete'][0])
    {
        return $this->v1AccountAccountidMediaMediaidDeleteAsyncWithHttpInfo($accountid, $mediaid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountAccountidMediaMediaidDeleteAsyncWithHttpInfo
     *
     * Delete Media
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string $mediaid Device ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaMediaidDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountidMediaMediaidDeleteAsyncWithHttpInfo($accountid, $mediaid, string $contentType = self::contentTypes['v1AccountAccountidMediaMediaidDelete'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle';
        $request = $this->v1AccountAccountidMediaMediaidDeleteRequest($accountid, $mediaid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountAccountidMediaMediaidDelete'
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string $mediaid Device ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaMediaidDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountAccountidMediaMediaidDeleteRequest($accountid, $mediaid, string $contentType = self::contentTypes['v1AccountAccountidMediaMediaidDelete'][0])
    {

        // verify the required parameter 'accountid' is set
        if ($accountid === null || (is_array($accountid) && count($accountid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accountid when calling v1AccountAccountidMediaMediaidDelete'
            );
        }

        // verify the required parameter 'mediaid' is set
        if ($mediaid === null || (is_array($mediaid) && count($mediaid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $mediaid when calling v1AccountAccountidMediaMediaidDelete'
            );
        }


        $resourcePath = '/v1/account/{accountid}/media/{mediaid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($accountid !== null) {
            $resourcePath = str_replace(
                '{' . 'accountid' . '}',
                ObjectSerializer::toPathValue($accountid),
                $resourcePath
            );
        }
        // path params
        if ($mediaid !== null) {
            $resourcePath = str_replace(
                '{' . 'mediaid' . '}',
                ObjectSerializer::toPathValue($mediaid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountAccountidMediaMediaidGet
     *
     * Get Media Details
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string $mediaid Media ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaMediaidGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ServiceDocsMediaGetSingle|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountAccountidMediaMediaidGet($accountid, $mediaid, string $contentType = self::contentTypes['v1AccountAccountidMediaMediaidGet'][0])
    {
        list($response) = $this->v1AccountAccountidMediaMediaidGetWithHttpInfo($accountid, $mediaid, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountAccountidMediaMediaidGetWithHttpInfo
     *
     * Get Media Details
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string $mediaid Media ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaMediaidGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ServiceDocsMediaGetSingle|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountAccountidMediaMediaidGetWithHttpInfo($accountid, $mediaid, string $contentType = self::contentTypes['v1AccountAccountidMediaMediaidGet'][0])
    {
        $request = $this->v1AccountAccountidMediaMediaidGetRequest($accountid, $mediaid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountAccountidMediaMediaidGetAsync
     *
     * Get Media Details
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string $mediaid Media ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaMediaidGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountidMediaMediaidGetAsync($accountid, $mediaid, string $contentType = self::contentTypes['v1AccountAccountidMediaMediaidGet'][0])
    {
        return $this->v1AccountAccountidMediaMediaidGetAsyncWithHttpInfo($accountid, $mediaid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountAccountidMediaMediaidGetAsyncWithHttpInfo
     *
     * Get Media Details
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string $mediaid Media ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaMediaidGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountidMediaMediaidGetAsyncWithHttpInfo($accountid, $mediaid, string $contentType = self::contentTypes['v1AccountAccountidMediaMediaidGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle';
        $request = $this->v1AccountAccountidMediaMediaidGetRequest($accountid, $mediaid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountAccountidMediaMediaidGet'
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string $mediaid Media ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaMediaidGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountAccountidMediaMediaidGetRequest($accountid, $mediaid, string $contentType = self::contentTypes['v1AccountAccountidMediaMediaidGet'][0])
    {

        // verify the required parameter 'accountid' is set
        if ($accountid === null || (is_array($accountid) && count($accountid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accountid when calling v1AccountAccountidMediaMediaidGet'
            );
        }

        // verify the required parameter 'mediaid' is set
        if ($mediaid === null || (is_array($mediaid) && count($mediaid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $mediaid when calling v1AccountAccountidMediaMediaidGet'
            );
        }


        $resourcePath = '/v1/account/{accountid}/media/{mediaid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($accountid !== null) {
            $resourcePath = str_replace(
                '{' . 'accountid' . '}',
                ObjectSerializer::toPathValue($accountid),
                $resourcePath
            );
        }
        // path params
        if ($mediaid !== null) {
            $resourcePath = str_replace(
                '{' . 'mediaid' . '}',
                ObjectSerializer::toPathValue($mediaid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountAccountidMediaPost
     *
     * Create Media
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  \OpenAPI\Client\Model\ServiceVOIPMediaAddEditData $media Media creation or update payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ServiceDocsMediaGetSingle|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountAccountidMediaPost($accountid, $media, string $contentType = self::contentTypes['v1AccountAccountidMediaPost'][0])
    {
        list($response) = $this->v1AccountAccountidMediaPostWithHttpInfo($accountid, $media, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountAccountidMediaPostWithHttpInfo
     *
     * Create Media
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  \OpenAPI\Client\Model\ServiceVOIPMediaAddEditData $media Media creation or update payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ServiceDocsMediaGetSingle|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountAccountidMediaPostWithHttpInfo($accountid, $media, string $contentType = self::contentTypes['v1AccountAccountidMediaPost'][0])
    {
        $request = $this->v1AccountAccountidMediaPostRequest($accountid, $media, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountAccountidMediaPostAsync
     *
     * Create Media
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  \OpenAPI\Client\Model\ServiceVOIPMediaAddEditData $media Media creation or update payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountidMediaPostAsync($accountid, $media, string $contentType = self::contentTypes['v1AccountAccountidMediaPost'][0])
    {
        return $this->v1AccountAccountidMediaPostAsyncWithHttpInfo($accountid, $media, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountAccountidMediaPostAsyncWithHttpInfo
     *
     * Create Media
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  \OpenAPI\Client\Model\ServiceVOIPMediaAddEditData $media Media creation or update payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountidMediaPostAsyncWithHttpInfo($accountid, $media, string $contentType = self::contentTypes['v1AccountAccountidMediaPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ServiceDocsMediaGetSingle';
        $request = $this->v1AccountAccountidMediaPostRequest($accountid, $media, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountAccountidMediaPost'
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  \OpenAPI\Client\Model\ServiceVOIPMediaAddEditData $media Media creation or update payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidMediaPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountAccountidMediaPostRequest($accountid, $media, string $contentType = self::contentTypes['v1AccountAccountidMediaPost'][0])
    {

        // verify the required parameter 'accountid' is set
        if ($accountid === null || (is_array($accountid) && count($accountid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accountid when calling v1AccountAccountidMediaPost'
            );
        }

        // verify the required parameter 'media' is set
        if ($media === null || (is_array($media) && count($media) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $media when calling v1AccountAccountidMediaPost'
            );
        }


        $resourcePath = '/v1/account/{accountid}/media';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($accountid !== null) {
            $resourcePath = str_replace(
                '{' . 'accountid' . '}',
                ObjectSerializer::toPathValue($accountid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($media)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($media));
            } else {
                $httpBody = $media;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
