<?php
/**
 * MenuApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * MenuApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MenuApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'v1AccountAccountIDMenuGet' => [
            'application/json',
        ],
        'v1AccountAccountIDMenuMenuIDDelete' => [
            'application/json',
        ],
        'v1AccountAccountIDMenuMenuIDGet' => [
            'application/json',
        ],
        'v1AccountAccountIDMenuMenuIDPut' => [
            'application/json',
        ],
        'v1AccountAccountIDMenuPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1AccountAccountIDMenuGet
     *
     * Get Menu List
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key start_key for pagination that was returned as next_start_key from your previous call (optional)
     * @param  int|null $page_size number of records to return, range 1 to 50 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\MenuOutputList|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountAccountIDMenuGet($account_id, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountIDMenuGet'][0])
    {
        list($response) = $this->v1AccountAccountIDMenuGetWithHttpInfo($account_id, $start_key, $page_size, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountAccountIDMenuGetWithHttpInfo
     *
     * Get Menu List
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key start_key for pagination that was returned as next_start_key from your previous call (optional)
     * @param  int|null $page_size number of records to return, range 1 to 50 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\MenuOutputList|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountAccountIDMenuGetWithHttpInfo($account_id, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountIDMenuGet'][0])
    {
        $request = $this->v1AccountAccountIDMenuGetRequest($account_id, $start_key, $page_size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\MenuOutputList',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\MenuOutputList',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\MenuOutputList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountAccountIDMenuGetAsync
     *
     * Get Menu List
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key start_key for pagination that was returned as next_start_key from your previous call (optional)
     * @param  int|null $page_size number of records to return, range 1 to 50 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMenuGetAsync($account_id, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountIDMenuGet'][0])
    {
        return $this->v1AccountAccountIDMenuGetAsyncWithHttpInfo($account_id, $start_key, $page_size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountAccountIDMenuGetAsyncWithHttpInfo
     *
     * Get Menu List
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key start_key for pagination that was returned as next_start_key from your previous call (optional)
     * @param  int|null $page_size number of records to return, range 1 to 50 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMenuGetAsyncWithHttpInfo($account_id, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountIDMenuGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\MenuOutputList';
        $request = $this->v1AccountAccountIDMenuGetRequest($account_id, $start_key, $page_size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountAccountIDMenuGet'
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key start_key for pagination that was returned as next_start_key from your previous call (optional)
     * @param  int|null $page_size number of records to return, range 1 to 50 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountAccountIDMenuGetRequest($account_id, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountIDMenuGet'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling v1AccountAccountIDMenuGet'
            );
        }




        $resourcePath = '/v1/account/{accountID}/menu';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_key,
            'start_key', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'page_size', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountID' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountAccountIDMenuMenuIDDelete
     *
     * Delete Menu
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDDelete'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\MenuOutputDetail|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountAccountIDMenuMenuIDDelete($account_id, $menu_id, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDDelete'][0])
    {
        list($response) = $this->v1AccountAccountIDMenuMenuIDDeleteWithHttpInfo($account_id, $menu_id, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountAccountIDMenuMenuIDDeleteWithHttpInfo
     *
     * Delete Menu
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDDelete'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\MenuOutputDetail|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountAccountIDMenuMenuIDDeleteWithHttpInfo($account_id, $menu_id, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDDelete'][0])
    {
        $request = $this->v1AccountAccountIDMenuMenuIDDeleteRequest($account_id, $menu_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\MenuOutputDetail',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\MenuOutputDetail',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\MenuOutputDetail',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountAccountIDMenuMenuIDDeleteAsync
     *
     * Delete Menu
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMenuMenuIDDeleteAsync($account_id, $menu_id, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDDelete'][0])
    {
        return $this->v1AccountAccountIDMenuMenuIDDeleteAsyncWithHttpInfo($account_id, $menu_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountAccountIDMenuMenuIDDeleteAsyncWithHttpInfo
     *
     * Delete Menu
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMenuMenuIDDeleteAsyncWithHttpInfo($account_id, $menu_id, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDDelete'][0])
    {
        $returnType = '\OpenAPI\Client\Model\MenuOutputDetail';
        $request = $this->v1AccountAccountIDMenuMenuIDDeleteRequest($account_id, $menu_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountAccountIDMenuMenuIDDelete'
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountAccountIDMenuMenuIDDeleteRequest($account_id, $menu_id, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDDelete'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling v1AccountAccountIDMenuMenuIDDelete'
            );
        }

        // verify the required parameter 'menu_id' is set
        if ($menu_id === null || (is_array($menu_id) && count($menu_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $menu_id when calling v1AccountAccountIDMenuMenuIDDelete'
            );
        }


        $resourcePath = '/v1/account/{accountID}/menu/{menuID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountID' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($menu_id !== null) {
            $resourcePath = str_replace(
                '{' . 'menuID' . '}',
                ObjectSerializer::toPathValue($menu_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountAccountIDMenuMenuIDGet
     *
     * Get Menu Details
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\MenuOutputDetail|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountAccountIDMenuMenuIDGet($account_id, $menu_id, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDGet'][0])
    {
        list($response) = $this->v1AccountAccountIDMenuMenuIDGetWithHttpInfo($account_id, $menu_id, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountAccountIDMenuMenuIDGetWithHttpInfo
     *
     * Get Menu Details
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\MenuOutputDetail|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountAccountIDMenuMenuIDGetWithHttpInfo($account_id, $menu_id, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDGet'][0])
    {
        $request = $this->v1AccountAccountIDMenuMenuIDGetRequest($account_id, $menu_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\MenuOutputDetail',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\MenuOutputDetail',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\MenuOutputDetail',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountAccountIDMenuMenuIDGetAsync
     *
     * Get Menu Details
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMenuMenuIDGetAsync($account_id, $menu_id, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDGet'][0])
    {
        return $this->v1AccountAccountIDMenuMenuIDGetAsyncWithHttpInfo($account_id, $menu_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountAccountIDMenuMenuIDGetAsyncWithHttpInfo
     *
     * Get Menu Details
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMenuMenuIDGetAsyncWithHttpInfo($account_id, $menu_id, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\MenuOutputDetail';
        $request = $this->v1AccountAccountIDMenuMenuIDGetRequest($account_id, $menu_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountAccountIDMenuMenuIDGet'
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountAccountIDMenuMenuIDGetRequest($account_id, $menu_id, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDGet'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling v1AccountAccountIDMenuMenuIDGet'
            );
        }

        // verify the required parameter 'menu_id' is set
        if ($menu_id === null || (is_array($menu_id) && count($menu_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $menu_id when calling v1AccountAccountIDMenuMenuIDGet'
            );
        }


        $resourcePath = '/v1/account/{accountID}/menu/{menuID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountID' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($menu_id !== null) {
            $resourcePath = str_replace(
                '{' . 'menuID' . '}',
                ObjectSerializer::toPathValue($menu_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountAccountIDMenuMenuIDPut
     *
     * Update Menu
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  \OpenAPI\Client\Model\MenuInputData $req_body payload fields (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\MenuOutputDetail|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountAccountIDMenuMenuIDPut($account_id, $menu_id, $req_body, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDPut'][0])
    {
        list($response) = $this->v1AccountAccountIDMenuMenuIDPutWithHttpInfo($account_id, $menu_id, $req_body, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountAccountIDMenuMenuIDPutWithHttpInfo
     *
     * Update Menu
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  \OpenAPI\Client\Model\MenuInputData $req_body payload fields (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\MenuOutputDetail|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountAccountIDMenuMenuIDPutWithHttpInfo($account_id, $menu_id, $req_body, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDPut'][0])
    {
        $request = $this->v1AccountAccountIDMenuMenuIDPutRequest($account_id, $menu_id, $req_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\MenuOutputDetail',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\MenuOutputDetail',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\MenuOutputDetail',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountAccountIDMenuMenuIDPutAsync
     *
     * Update Menu
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  \OpenAPI\Client\Model\MenuInputData $req_body payload fields (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMenuMenuIDPutAsync($account_id, $menu_id, $req_body, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDPut'][0])
    {
        return $this->v1AccountAccountIDMenuMenuIDPutAsyncWithHttpInfo($account_id, $menu_id, $req_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountAccountIDMenuMenuIDPutAsyncWithHttpInfo
     *
     * Update Menu
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  \OpenAPI\Client\Model\MenuInputData $req_body payload fields (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMenuMenuIDPutAsyncWithHttpInfo($account_id, $menu_id, $req_body, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDPut'][0])
    {
        $returnType = '\OpenAPI\Client\Model\MenuOutputDetail';
        $request = $this->v1AccountAccountIDMenuMenuIDPutRequest($account_id, $menu_id, $req_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountAccountIDMenuMenuIDPut'
     *
     * @param  string $account_id Account ID, 32 alpha numeric (required)
     * @param  string $menu_id Menu ID, 32 alpha numeric (required)
     * @param  \OpenAPI\Client\Model\MenuInputData $req_body payload fields (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuMenuIDPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountAccountIDMenuMenuIDPutRequest($account_id, $menu_id, $req_body, string $contentType = self::contentTypes['v1AccountAccountIDMenuMenuIDPut'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling v1AccountAccountIDMenuMenuIDPut'
            );
        }

        // verify the required parameter 'menu_id' is set
        if ($menu_id === null || (is_array($menu_id) && count($menu_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $menu_id when calling v1AccountAccountIDMenuMenuIDPut'
            );
        }

        // verify the required parameter 'req_body' is set
        if ($req_body === null || (is_array($req_body) && count($req_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $req_body when calling v1AccountAccountIDMenuMenuIDPut'
            );
        }


        $resourcePath = '/v1/account/{accountID}/menu/{menuID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountID' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($menu_id !== null) {
            $resourcePath = str_replace(
                '{' . 'menuID' . '}',
                ObjectSerializer::toPathValue($menu_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($req_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($req_body));
            } else {
                $httpBody = $req_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountAccountIDMenuPost
     *
     * Create Menu
     *
     * @param  string $account_id Account ID, 32 alphanumeric (required)
     * @param  \OpenAPI\Client\Model\MenuInputData $menu Menu data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\MenuOutputDetail|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountAccountIDMenuPost($account_id, $menu, string $contentType = self::contentTypes['v1AccountAccountIDMenuPost'][0])
    {
        list($response) = $this->v1AccountAccountIDMenuPostWithHttpInfo($account_id, $menu, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountAccountIDMenuPostWithHttpInfo
     *
     * Create Menu
     *
     * @param  string $account_id Account ID, 32 alphanumeric (required)
     * @param  \OpenAPI\Client\Model\MenuInputData $menu Menu data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\MenuOutputDetail|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountAccountIDMenuPostWithHttpInfo($account_id, $menu, string $contentType = self::contentTypes['v1AccountAccountIDMenuPost'][0])
    {
        $request = $this->v1AccountAccountIDMenuPostRequest($account_id, $menu, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\MenuOutputDetail',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\MenuOutputDetail',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\MenuOutputDetail',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountAccountIDMenuPostAsync
     *
     * Create Menu
     *
     * @param  string $account_id Account ID, 32 alphanumeric (required)
     * @param  \OpenAPI\Client\Model\MenuInputData $menu Menu data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMenuPostAsync($account_id, $menu, string $contentType = self::contentTypes['v1AccountAccountIDMenuPost'][0])
    {
        return $this->v1AccountAccountIDMenuPostAsyncWithHttpInfo($account_id, $menu, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountAccountIDMenuPostAsyncWithHttpInfo
     *
     * Create Menu
     *
     * @param  string $account_id Account ID, 32 alphanumeric (required)
     * @param  \OpenAPI\Client\Model\MenuInputData $menu Menu data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountIDMenuPostAsyncWithHttpInfo($account_id, $menu, string $contentType = self::contentTypes['v1AccountAccountIDMenuPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\MenuOutputDetail';
        $request = $this->v1AccountAccountIDMenuPostRequest($account_id, $menu, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountAccountIDMenuPost'
     *
     * @param  string $account_id Account ID, 32 alphanumeric (required)
     * @param  \OpenAPI\Client\Model\MenuInputData $menu Menu data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountIDMenuPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountAccountIDMenuPostRequest($account_id, $menu, string $contentType = self::contentTypes['v1AccountAccountIDMenuPost'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling v1AccountAccountIDMenuPost'
            );
        }

        // verify the required parameter 'menu' is set
        if ($menu === null || (is_array($menu) && count($menu) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $menu when calling v1AccountAccountIDMenuPost'
            );
        }


        $resourcePath = '/v1/account/{accountID}/menu';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountID' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($menu)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($menu));
            } else {
                $httpBody = $menu;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
