<?php
/**
 * PhoneNumberApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * PhoneNumberApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PhoneNumberApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'v1AccountAccountidPhonenumberGet' => [
            'application/json',
        ],
        'v1AccountPhonenumberAssignPost' => [
            'application/json',
        ],
        'v1AccountPhonenumberDisconnectPost' => [
            'application/json',
        ],
        'v1AccountPhonenumberGet' => [
            'application/json',
        ],
        'v1AccountPhonenumberPost' => [
            'application/json',
        ],
        'v1AccountPhonenumberUnassignPost' => [
            'application/json',
        ],
        'v1PhonenumberSearchGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1AccountAccountidPhonenumberGet
     *
     * Get Assigned Numbers List
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key Start key for pagination, obtained from previous responses (optional)
     * @param  int|null $page_size Number of records to return per page (range: 1 to 50) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidPhonenumberGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ServiceDocsAccountPhonenumberGetAll|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountAccountidPhonenumberGet($accountid, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountidPhonenumberGet'][0])
    {
        list($response) = $this->v1AccountAccountidPhonenumberGetWithHttpInfo($accountid, $start_key, $page_size, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountAccountidPhonenumberGetWithHttpInfo
     *
     * Get Assigned Numbers List
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key Start key for pagination, obtained from previous responses (optional)
     * @param  int|null $page_size Number of records to return per page (range: 1 to 50) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidPhonenumberGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ServiceDocsAccountPhonenumberGetAll|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountAccountidPhonenumberGetWithHttpInfo($accountid, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountidPhonenumberGet'][0])
    {
        $request = $this->v1AccountAccountidPhonenumberGetRequest($accountid, $start_key, $page_size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ServiceDocsAccountPhonenumberGetAll',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ServiceDocsAccountPhonenumberGetAll',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ServiceDocsAccountPhonenumberGetAll',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountAccountidPhonenumberGetAsync
     *
     * Get Assigned Numbers List
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key Start key for pagination, obtained from previous responses (optional)
     * @param  int|null $page_size Number of records to return per page (range: 1 to 50) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidPhonenumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountidPhonenumberGetAsync($accountid, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountidPhonenumberGet'][0])
    {
        return $this->v1AccountAccountidPhonenumberGetAsyncWithHttpInfo($accountid, $start_key, $page_size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountAccountidPhonenumberGetAsyncWithHttpInfo
     *
     * Get Assigned Numbers List
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key Start key for pagination, obtained from previous responses (optional)
     * @param  int|null $page_size Number of records to return per page (range: 1 to 50) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidPhonenumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountAccountidPhonenumberGetAsyncWithHttpInfo($accountid, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountidPhonenumberGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ServiceDocsAccountPhonenumberGetAll';
        $request = $this->v1AccountAccountidPhonenumberGetRequest($accountid, $start_key, $page_size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountAccountidPhonenumberGet'
     *
     * @param  string $accountid Account ID, 32 alpha numeric (required)
     * @param  string|null $start_key Start key for pagination, obtained from previous responses (optional)
     * @param  int|null $page_size Number of records to return per page (range: 1 to 50) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountAccountidPhonenumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountAccountidPhonenumberGetRequest($accountid, $start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountAccountidPhonenumberGet'][0])
    {

        // verify the required parameter 'accountid' is set
        if ($accountid === null || (is_array($accountid) && count($accountid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accountid when calling v1AccountAccountidPhonenumberGet'
            );
        }




        $resourcePath = '/v1/account/{accountid}/phonenumber';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_key,
            'start_key', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'page_size', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($accountid !== null) {
            $resourcePath = str_replace(
                '{' . 'accountid' . '}',
                ObjectSerializer::toPathValue($accountid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountPhonenumberAssignPost
     *
     * Assign Number
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberAssignPayload $payload assignment payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberAssignPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountPhonenumberAssignPost($payload, string $contentType = self::contentTypes['v1AccountPhonenumberAssignPost'][0])
    {
        list($response) = $this->v1AccountPhonenumberAssignPostWithHttpInfo($payload, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountPhonenumberAssignPostWithHttpInfo
     *
     * Assign Number
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberAssignPayload $payload assignment payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberAssignPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountPhonenumberAssignPostWithHttpInfo($payload, string $contentType = self::contentTypes['v1AccountPhonenumberAssignPost'][0])
    {
        $request = $this->v1AccountPhonenumberAssignPostRequest($payload, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountPhonenumberAssignPostAsync
     *
     * Assign Number
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberAssignPayload $payload assignment payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberAssignPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountPhonenumberAssignPostAsync($payload, string $contentType = self::contentTypes['v1AccountPhonenumberAssignPost'][0])
    {
        return $this->v1AccountPhonenumberAssignPostAsyncWithHttpInfo($payload, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountPhonenumberAssignPostAsyncWithHttpInfo
     *
     * Assign Number
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberAssignPayload $payload assignment payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberAssignPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountPhonenumberAssignPostAsyncWithHttpInfo($payload, string $contentType = self::contentTypes['v1AccountPhonenumberAssignPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly';
        $request = $this->v1AccountPhonenumberAssignPostRequest($payload, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountPhonenumberAssignPost'
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberAssignPayload $payload assignment payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberAssignPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountPhonenumberAssignPostRequest($payload, string $contentType = self::contentTypes['v1AccountPhonenumberAssignPost'][0])
    {

        // verify the required parameter 'payload' is set
        if ($payload === null || (is_array($payload) && count($payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payload when calling v1AccountPhonenumberAssignPost'
            );
        }


        $resourcePath = '/v1/account/phonenumber/assign';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($payload));
            } else {
                $httpBody = $payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountPhonenumberDisconnectPost
     *
     * Disconnect Number
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberUnassignPayload $payload disconnect payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberDisconnectPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountPhonenumberDisconnectPost($payload, string $contentType = self::contentTypes['v1AccountPhonenumberDisconnectPost'][0])
    {
        list($response) = $this->v1AccountPhonenumberDisconnectPostWithHttpInfo($payload, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountPhonenumberDisconnectPostWithHttpInfo
     *
     * Disconnect Number
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberUnassignPayload $payload disconnect payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberDisconnectPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountPhonenumberDisconnectPostWithHttpInfo($payload, string $contentType = self::contentTypes['v1AccountPhonenumberDisconnectPost'][0])
    {
        $request = $this->v1AccountPhonenumberDisconnectPostRequest($payload, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountPhonenumberDisconnectPostAsync
     *
     * Disconnect Number
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberUnassignPayload $payload disconnect payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberDisconnectPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountPhonenumberDisconnectPostAsync($payload, string $contentType = self::contentTypes['v1AccountPhonenumberDisconnectPost'][0])
    {
        return $this->v1AccountPhonenumberDisconnectPostAsyncWithHttpInfo($payload, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountPhonenumberDisconnectPostAsyncWithHttpInfo
     *
     * Disconnect Number
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberUnassignPayload $payload disconnect payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberDisconnectPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountPhonenumberDisconnectPostAsyncWithHttpInfo($payload, string $contentType = self::contentTypes['v1AccountPhonenumberDisconnectPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly';
        $request = $this->v1AccountPhonenumberDisconnectPostRequest($payload, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountPhonenumberDisconnectPost'
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberUnassignPayload $payload disconnect payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberDisconnectPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountPhonenumberDisconnectPostRequest($payload, string $contentType = self::contentTypes['v1AccountPhonenumberDisconnectPost'][0])
    {

        // verify the required parameter 'payload' is set
        if ($payload === null || (is_array($payload) && count($payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payload when calling v1AccountPhonenumberDisconnectPost'
            );
        }


        $resourcePath = '/v1/account/phonenumber/disconnect';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($payload));
            } else {
                $httpBody = $payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountPhonenumberGet
     *
     * Get Unassigned Numbers List
     *
     * @param  string|null $start_key Start key for pagination, obtained from previous responses (optional)
     * @param  int|null $page_size Number of records to return per page (range: 1 to 50) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ServiceDocsAccountPhonenumberGetAll|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountPhonenumberGet($start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountPhonenumberGet'][0])
    {
        list($response) = $this->v1AccountPhonenumberGetWithHttpInfo($start_key, $page_size, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountPhonenumberGetWithHttpInfo
     *
     * Get Unassigned Numbers List
     *
     * @param  string|null $start_key Start key for pagination, obtained from previous responses (optional)
     * @param  int|null $page_size Number of records to return per page (range: 1 to 50) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ServiceDocsAccountPhonenumberGetAll|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountPhonenumberGetWithHttpInfo($start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountPhonenumberGet'][0])
    {
        $request = $this->v1AccountPhonenumberGetRequest($start_key, $page_size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ServiceDocsAccountPhonenumberGetAll',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ServiceDocsAccountPhonenumberGetAll',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ServiceDocsAccountPhonenumberGetAll',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountPhonenumberGetAsync
     *
     * Get Unassigned Numbers List
     *
     * @param  string|null $start_key Start key for pagination, obtained from previous responses (optional)
     * @param  int|null $page_size Number of records to return per page (range: 1 to 50) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountPhonenumberGetAsync($start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountPhonenumberGet'][0])
    {
        return $this->v1AccountPhonenumberGetAsyncWithHttpInfo($start_key, $page_size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountPhonenumberGetAsyncWithHttpInfo
     *
     * Get Unassigned Numbers List
     *
     * @param  string|null $start_key Start key for pagination, obtained from previous responses (optional)
     * @param  int|null $page_size Number of records to return per page (range: 1 to 50) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountPhonenumberGetAsyncWithHttpInfo($start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountPhonenumberGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ServiceDocsAccountPhonenumberGetAll';
        $request = $this->v1AccountPhonenumberGetRequest($start_key, $page_size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountPhonenumberGet'
     *
     * @param  string|null $start_key Start key for pagination, obtained from previous responses (optional)
     * @param  int|null $page_size Number of records to return per page (range: 1 to 50) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountPhonenumberGetRequest($start_key = null, $page_size = null, string $contentType = self::contentTypes['v1AccountPhonenumberGet'][0])
    {




        $resourcePath = '/v1/account/phonenumber';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_key,
            'start_key', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'page_size', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountPhonenumberPost
     *
     * Purchase Number
     *
     * @param  string[] $phonenumber phonenumber fields (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ServiceDocsOrderPhonenumber|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountPhonenumberPost($phonenumber, string $contentType = self::contentTypes['v1AccountPhonenumberPost'][0])
    {
        list($response) = $this->v1AccountPhonenumberPostWithHttpInfo($phonenumber, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountPhonenumberPostWithHttpInfo
     *
     * Purchase Number
     *
     * @param  string[] $phonenumber phonenumber fields (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ServiceDocsOrderPhonenumber|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountPhonenumberPostWithHttpInfo($phonenumber, string $contentType = self::contentTypes['v1AccountPhonenumberPost'][0])
    {
        $request = $this->v1AccountPhonenumberPostRequest($phonenumber, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ServiceDocsOrderPhonenumber',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ServiceDocsOrderPhonenumber',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ServiceDocsOrderPhonenumber',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountPhonenumberPostAsync
     *
     * Purchase Number
     *
     * @param  string[] $phonenumber phonenumber fields (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountPhonenumberPostAsync($phonenumber, string $contentType = self::contentTypes['v1AccountPhonenumberPost'][0])
    {
        return $this->v1AccountPhonenumberPostAsyncWithHttpInfo($phonenumber, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountPhonenumberPostAsyncWithHttpInfo
     *
     * Purchase Number
     *
     * @param  string[] $phonenumber phonenumber fields (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountPhonenumberPostAsyncWithHttpInfo($phonenumber, string $contentType = self::contentTypes['v1AccountPhonenumberPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ServiceDocsOrderPhonenumber';
        $request = $this->v1AccountPhonenumberPostRequest($phonenumber, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountPhonenumberPost'
     *
     * @param  string[] $phonenumber phonenumber fields (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountPhonenumberPostRequest($phonenumber, string $contentType = self::contentTypes['v1AccountPhonenumberPost'][0])
    {

        // verify the required parameter 'phonenumber' is set
        if ($phonenumber === null || (is_array($phonenumber) && count($phonenumber) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $phonenumber when calling v1AccountPhonenumberPost'
            );
        }


        $resourcePath = '/v1/account/phonenumber';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($phonenumber)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($phonenumber));
            } else {
                $httpBody = $phonenumber;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AccountPhonenumberUnassignPost
     *
     * Unassign Number
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberUnassignPayload $payload unassign payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberUnassignPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly|\OpenAPI\Client\Model\CPAASError
     */
    public function v1AccountPhonenumberUnassignPost($payload, string $contentType = self::contentTypes['v1AccountPhonenumberUnassignPost'][0])
    {
        list($response) = $this->v1AccountPhonenumberUnassignPostWithHttpInfo($payload, $contentType);
        return $response;
    }

    /**
     * Operation v1AccountPhonenumberUnassignPostWithHttpInfo
     *
     * Unassign Number
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberUnassignPayload $payload unassign payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberUnassignPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AccountPhonenumberUnassignPostWithHttpInfo($payload, string $contentType = self::contentTypes['v1AccountPhonenumberUnassignPost'][0])
    {
        $request = $this->v1AccountPhonenumberUnassignPostRequest($payload, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AccountPhonenumberUnassignPostAsync
     *
     * Unassign Number
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberUnassignPayload $payload unassign payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberUnassignPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountPhonenumberUnassignPostAsync($payload, string $contentType = self::contentTypes['v1AccountPhonenumberUnassignPost'][0])
    {
        return $this->v1AccountPhonenumberUnassignPostAsyncWithHttpInfo($payload, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AccountPhonenumberUnassignPostAsyncWithHttpInfo
     *
     * Unassign Number
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberUnassignPayload $payload unassign payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberUnassignPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AccountPhonenumberUnassignPostAsyncWithHttpInfo($payload, string $contentType = self::contentTypes['v1AccountPhonenumberUnassignPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ServiceAPIResponseStatusCodeOnly';
        $request = $this->v1AccountPhonenumberUnassignPostRequest($payload, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AccountPhonenumberUnassignPost'
     *
     * @param  \OpenAPI\Client\Model\ServiceDocsPhonenumberUnassignPayload $payload unassign payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AccountPhonenumberUnassignPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AccountPhonenumberUnassignPostRequest($payload, string $contentType = self::contentTypes['v1AccountPhonenumberUnassignPost'][0])
    {

        // verify the required parameter 'payload' is set
        if ($payload === null || (is_array($payload) && count($payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payload when calling v1AccountPhonenumberUnassignPost'
            );
        }


        $resourcePath = '/v1/account/phonenumber/unassign';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($payload));
            } else {
                $httpBody = $payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1PhonenumberSearchGet
     *
     * Search New Numbers
     *
     * @param  string $area_code Area code (exactly 3 numeric characters) example: 610 or 484 (required)
     * @param  int|null $quantity Number of records to return (range: 1 to 100, defaults to 100 if not provided) (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PhonenumberSearchGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ServiceDocsPhonenumberSearchGetAll|\OpenAPI\Client\Model\CPAASError
     */
    public function v1PhonenumberSearchGet($area_code, $quantity = 100, string $contentType = self::contentTypes['v1PhonenumberSearchGet'][0])
    {
        list($response) = $this->v1PhonenumberSearchGetWithHttpInfo($area_code, $quantity, $contentType);
        return $response;
    }

    /**
     * Operation v1PhonenumberSearchGetWithHttpInfo
     *
     * Search New Numbers
     *
     * @param  string $area_code Area code (exactly 3 numeric characters) example: 610 or 484 (required)
     * @param  int|null $quantity Number of records to return (range: 1 to 100, defaults to 100 if not provided) (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PhonenumberSearchGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ServiceDocsPhonenumberSearchGetAll|\OpenAPI\Client\Model\CPAASError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1PhonenumberSearchGetWithHttpInfo($area_code, $quantity = 100, string $contentType = self::contentTypes['v1PhonenumberSearchGet'][0])
    {
        $request = $this->v1PhonenumberSearchGetRequest($area_code, $quantity, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ServiceDocsPhonenumberSearchGetAll',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CPAASError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ServiceDocsPhonenumberSearchGetAll',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ServiceDocsPhonenumberSearchGetAll',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CPAASError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1PhonenumberSearchGetAsync
     *
     * Search New Numbers
     *
     * @param  string $area_code Area code (exactly 3 numeric characters) example: 610 or 484 (required)
     * @param  int|null $quantity Number of records to return (range: 1 to 100, defaults to 100 if not provided) (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PhonenumberSearchGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1PhonenumberSearchGetAsync($area_code, $quantity = 100, string $contentType = self::contentTypes['v1PhonenumberSearchGet'][0])
    {
        return $this->v1PhonenumberSearchGetAsyncWithHttpInfo($area_code, $quantity, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1PhonenumberSearchGetAsyncWithHttpInfo
     *
     * Search New Numbers
     *
     * @param  string $area_code Area code (exactly 3 numeric characters) example: 610 or 484 (required)
     * @param  int|null $quantity Number of records to return (range: 1 to 100, defaults to 100 if not provided) (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PhonenumberSearchGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1PhonenumberSearchGetAsyncWithHttpInfo($area_code, $quantity = 100, string $contentType = self::contentTypes['v1PhonenumberSearchGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ServiceDocsPhonenumberSearchGetAll';
        $request = $this->v1PhonenumberSearchGetRequest($area_code, $quantity, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1PhonenumberSearchGet'
     *
     * @param  string $area_code Area code (exactly 3 numeric characters) example: 610 or 484 (required)
     * @param  int|null $quantity Number of records to return (range: 1 to 100, defaults to 100 if not provided) (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1PhonenumberSearchGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1PhonenumberSearchGetRequest($area_code, $quantity = 100, string $contentType = self::contentTypes['v1PhonenumberSearchGet'][0])
    {

        // verify the required parameter 'area_code' is set
        if ($area_code === null || (is_array($area_code) && count($area_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $area_code when calling v1PhonenumberSearchGet'
            );
        }



        $resourcePath = '/v1/phonenumber/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $area_code,
            'area_code', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $quantity,
            'quantity', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
