<?php
/**
 * ServiceSystemStatusVOIPService
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceSystemStatusVOIPService Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ServiceSystemStatusVOIPService implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'service.SystemStatusVOIPService';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'apps' => 'string',
        'backend' => 'string',
        'call_manager' => 'string',
        'media_server' => 'string',
        'message_broker' => 'string',
        'sip_proxy' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'apps' => null,
        'backend' => null,
        'call_manager' => null,
        'media_server' => null,
        'message_broker' => null,
        'sip_proxy' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'apps' => false,
        'backend' => false,
        'call_manager' => false,
        'media_server' => false,
        'message_broker' => false,
        'sip_proxy' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'apps' => 'apps',
        'backend' => 'backend',
        'call_manager' => 'call_manager',
        'media_server' => 'media_server',
        'message_broker' => 'message_broker',
        'sip_proxy' => 'sip_proxy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'apps' => 'setApps',
        'backend' => 'setBackend',
        'call_manager' => 'setCallManager',
        'media_server' => 'setMediaServer',
        'message_broker' => 'setMessageBroker',
        'sip_proxy' => 'setSipProxy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'apps' => 'getApps',
        'backend' => 'getBackend',
        'call_manager' => 'getCallManager',
        'media_server' => 'getMediaServer',
        'message_broker' => 'getMessageBroker',
        'sip_proxy' => 'getSipProxy'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('apps', $data ?? [], null);
        $this->setIfExists('backend', $data ?? [], null);
        $this->setIfExists('call_manager', $data ?? [], null);
        $this->setIfExists('media_server', $data ?? [], null);
        $this->setIfExists('message_broker', $data ?? [], null);
        $this->setIfExists('sip_proxy', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets apps
     *
     * @return string|null
     */
    public function getApps()
    {
        return $this->container['apps'];
    }

    /**
     * Sets apps
     *
     * @param string|null $apps apps
     *
     * @return self
     */
    public function setApps($apps)
    {
        if (is_null($apps)) {
            throw new \InvalidArgumentException('non-nullable apps cannot be null');
        }
        $this->container['apps'] = $apps;

        return $this;
    }

    /**
     * Gets backend
     *
     * @return string|null
     */
    public function getBackend()
    {
        return $this->container['backend'];
    }

    /**
     * Sets backend
     *
     * @param string|null $backend backend
     *
     * @return self
     */
    public function setBackend($backend)
    {
        if (is_null($backend)) {
            throw new \InvalidArgumentException('non-nullable backend cannot be null');
        }
        $this->container['backend'] = $backend;

        return $this;
    }

    /**
     * Gets call_manager
     *
     * @return string|null
     */
    public function getCallManager()
    {
        return $this->container['call_manager'];
    }

    /**
     * Sets call_manager
     *
     * @param string|null $call_manager call_manager
     *
     * @return self
     */
    public function setCallManager($call_manager)
    {
        if (is_null($call_manager)) {
            throw new \InvalidArgumentException('non-nullable call_manager cannot be null');
        }
        $this->container['call_manager'] = $call_manager;

        return $this;
    }

    /**
     * Gets media_server
     *
     * @return string|null
     */
    public function getMediaServer()
    {
        return $this->container['media_server'];
    }

    /**
     * Sets media_server
     *
     * @param string|null $media_server media_server
     *
     * @return self
     */
    public function setMediaServer($media_server)
    {
        if (is_null($media_server)) {
            throw new \InvalidArgumentException('non-nullable media_server cannot be null');
        }
        $this->container['media_server'] = $media_server;

        return $this;
    }

    /**
     * Gets message_broker
     *
     * @return string|null
     */
    public function getMessageBroker()
    {
        return $this->container['message_broker'];
    }

    /**
     * Sets message_broker
     *
     * @param string|null $message_broker message_broker
     *
     * @return self
     */
    public function setMessageBroker($message_broker)
    {
        if (is_null($message_broker)) {
            throw new \InvalidArgumentException('non-nullable message_broker cannot be null');
        }
        $this->container['message_broker'] = $message_broker;

        return $this;
    }

    /**
     * Gets sip_proxy
     *
     * @return string|null
     */
    public function getSipProxy()
    {
        return $this->container['sip_proxy'];
    }

    /**
     * Sets sip_proxy
     *
     * @param string|null $sip_proxy sip_proxy
     *
     * @return self
     */
    public function setSipProxy($sip_proxy)
    {
        if (is_null($sip_proxy)) {
            throw new \InvalidArgumentException('non-nullable sip_proxy cannot be null');
        }
        $this->container['sip_proxy'] = $sip_proxy;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


