<?php
/**
 * MediaApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MediaApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MediaApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1AccountAccountIDMediaMediaIDFileGet
     *
     * Get Media File.
     *
     */
    public function testV1AccountAccountIDMediaMediaIDFileGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountAccountIDMediaMediaIDFilePost
     *
     * Add Media File.
     *
     */
    public function testV1AccountAccountIDMediaMediaIDFilePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountAccountidMediaGet
     *
     * Get Media List.
     *
     */
    public function testV1AccountAccountidMediaGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountAccountidMediaMediaidDelete
     *
     * Delete Media.
     *
     */
    public function testV1AccountAccountidMediaMediaidDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountAccountidMediaMediaidGet
     *
     * Get Media Details.
     *
     */
    public function testV1AccountAccountidMediaMediaidGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountAccountidMediaPost
     *
     * Create Media.
     *
     */
    public function testV1AccountAccountidMediaPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
