<?php
/**
 * ProvisioningApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProvisioningApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProvisioningApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1ApBrandBrandFamilyFamilyGet
     *
     * Get Family.
     *
     */
    public function testV1ApBrandBrandFamilyFamilyGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ApBrandBrandFamilyFamilyModelGet
     *
     * Get Model List.
     *
     */
    public function testV1ApBrandBrandFamilyFamilyModelGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ApBrandBrandFamilyFamilyModelModelGet
     *
     * Get Model.
     *
     */
    public function testV1ApBrandBrandFamilyFamilyModelModelGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ApBrandBrandFamilyFamilyModelModelTemplateGet
     *
     * Get Template List.
     *
     */
    public function testV1ApBrandBrandFamilyFamilyModelModelTemplateGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ApBrandBrandFamilyFamilyModelModelTemplateTemplateGet
     *
     * Get Template.
     *
     */
    public function testV1ApBrandBrandFamilyFamilyModelModelTemplateTemplateGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ApBrandBrandFamilyGet
     *
     * Get Family List.
     *
     */
    public function testV1ApBrandBrandFamilyGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ApBrandBrandGet
     *
     * Get Brand.
     *
     */
    public function testV1ApBrandBrandGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ApBrandGet
     *
     * Get Brand.
     *
     */
    public function testV1ApBrandGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ApConfigfileGeneratePost
     *
     * Generate config file.
     *
     */
    public function testV1ApConfigfileGeneratePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
