<?php
/**
 * SMSApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SMSApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SMSApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1SmsAccountAccountIDCampaignCampaignIDImportGet
     *
     * .
     *
     */
    public function testV1SmsAccountAccountIDCampaignCampaignIDImportGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1SmsAccountAccountIDCampaignCampaignIDImportPost
     *
     * .
     *
     */
    public function testV1SmsAccountAccountIDCampaignCampaignIDImportPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1SmsAccountAccountIDCampaignCampaignIDPhonenumberGet
     *
     * .
     *
     */
    public function testV1SmsAccountAccountIDCampaignCampaignIDPhonenumberGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1SmsAccountAccountIDCampaignCampaignIDPhonenumberPut
     *
     * .
     *
     */
    public function testV1SmsAccountAccountIDCampaignCampaignIDPhonenumberPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1SmsAccountAccountIDCampaignImportGet
     *
     * .
     *
     */
    public function testV1SmsAccountAccountIDCampaignImportGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
